### ISSUE TITLE
`.\:popover-open` is an invalid selector?

### ISSUE THREAD

**Issue by jpzwarte** [oddbird/popover-polyfill#109]
So according to the docs, the `.\:popover-open` selector should work in browsers where `popover` isn't supported yet. I can confirm that in Safari & Firefox, the class is added to the popover element. However, also in Safari & Firefox, the style rule is *never* applied. Perhaps because this selector is invalid?

**Comment by jgerigmeyer** [comment]
@jpzwarte Hm, I can't seem to reproduce this. In both Safari and Firefox I'm seeing `.\:popover-open` style rules applied as expected -- e.g. the `[popover]:not(.\:popover-open) { display: none; }` rule in the [demo site](https://popover-polyfill.netlify.app/).

![Screenshot 2023-06-28 at 12 09 57 PM](https://github.com/oddbird/popover-polyfill/assets/552316/0510dc6c-0b67-415d-800c-61ed422329d4)

Can you push a reproducible test case?

**Comment by jpzwarte** [comment]
@jgerigmeyer https://codepen.io/jpzwarte/pen/dyQvRrX

Apparently the `:popover-open` class does not working within the shadow DOM.

**Comment by jpzwarte** [comment]
Closing, it needs a double backslash 🤦‍♂️
