### ISSUE TITLE
Events on slotted elements behave unpredictable

### ISSUE THREAD

**Issue by Diaan** [oddbird/popover-polyfill#112]
I'm working on a select component with a button that opens the "dropdown", made with a dialog[popover], using `popovertarget`.
In the dialog i have options that are clickable so you can select one of them, and when you do the dropdown closes.
When testing this i ran into some inconsistencies in how it works across browsers.
I've made a simplified version of my component available here: https://main--symphonious-croissant-e608ab.netlify.app/
The code can be seen here: https://stackblitz.com/edit/vitejs-vite-yu5jkd?file=src%2Fmy-element.ts
The little counter in the option should increase with every click (and is persisted also when closing the dialog)

The difference between the options is that one is placed in the dialog via a `slot` and the other one directly.

- In chrome (114) you can click both options and none of them close the dialog. The counter is increased in both options.
- In Firefox and Safari both the options increase the counter when clicked, but the slotted option closes the dialog.
- In Safari (and chrome) on iPhone the "direct" option works the same; counter increases and dialog stays open, but the slotted one doesn't seem to register the click on the element; the counter is not increased and the dialog is closed.

I couldn't find an existing issue regarding slotted elements and was wondering is this is at all supported or whether this is a bug?

**Comment by thejackshelton** [comment]
Hey @Diaan! Were you able to find a workaround for this? Or was it specific to a certain framework?

**Comment by Diaan** [comment]
> Hey @Diaan! Were you able to find a workaround for this? Or was it specific to a certain framework?

No, we haven't found a work-around yet, it still doesn't work.
We are using Lit, I haven't tried it in vanilla JS yet, but from what I understand Lit doesn't add/change that much functionality in runtime.

**Comment by Diaan** [comment]
Not sure which version (or iPhone update) fixed it, but it seems to be working now!
