### ISSUE TITLE
Why doesn't the polyfill move the popover to top-layer?

### ISSUE THREAD

**Issue by wmertens** [oddbird/popover-polyfill#122]
Is there a reason why this can't or won't be done? CSS or something?

**Comment by reify-benjamin-solum** [comment]
I believe Popover and Top Layer shipped together in browsers so in the event that this polyfill is needed there is no top layer to add anything to.

Also, [from mdn](https://developer.mozilla.org/en-US/docs/Glossary/Top_layer):

> Note that the top layer is an internal browser concept and cannot be directly manipulated from code.

**Comment by wmertens** [comment]
Right, I meant that it would add a div to the body and move the popover element into it, but that may wreak havoc on frameworks so it's not really an option.
