### ISSUE TITLE
Polyfill doesn't seem to work with dialog element

### ISSUE THREAD

**Issue by samGbos** [oddbird/popover-polyfill#198]
I was trying to set a `<dialog>` to be a popover as discussed here: https://hidde.blog/popover-semantics/

However, this doesn't seem to work in Firefox; the popover does seem to work with a `<div>` element though:
https://codepen.io/codepenguy131/pen/jORdKGo

**Comment by jgerigmeyer** [comment]
@samGbos Thanks for reporting! It looks to me like that's a bug -- I've submitted a fix in #199: https://deploy-preview-199--popover-polyfill.netlify.app/

**Comment by samGbos** [comment]
Amazing, thanks! Such a quick response!

**Comment by jgerigmeyer** [comment]
@samGbos Released in [v0.4.2](https://github.com/oddbird/popover-polyfill/releases/tag/v0.4.2)
