### ISSUE TITLE
Is there a way to FORCE use of the polyfill on Safari 17?

### ISSUE THREAD

**Issue by williamsdyyz** [oddbird/popover-polyfill#212]
I ask because the Safari implementation is buggy and the polyfill works better!

**Comment by jgerigmeyer** [comment]
I haven't tested it, but if you have a way to determine whether your code is running in Safari 17 (or a way to identify a particular "bugginess"), I think you could import the `apply` method directly and skip the `isSupported` check:

```js
import { apply, isSupported } from '@oddbird/popover-polyfill/fn';

if (isSafari17 || !isSupported()) {
  apply();
}
```

**Comment by williamsdyyz** [comment]
Interesting idea. I'll see what happens.  Thanks

**Comment by Techn1x** [comment]
I've hit this as well.

Safari 17 is broken for popovers if the trigger is a button that appears inside a form (Safari incorrectly handles it as a submit event, and the popover does not show). They fix this in Safari 18.2, among other fixes for popover api.

This polyfill has worfked great for all prior versions of Safari, so I tried applying this polyfill to Safari 17, but then popovers don't open at all anywhere. Same with any other browsers if I try to `apply()` the polyfill when Popover API is already supported by the browser.

Do you think it would be possible to, if `apply()` is called, override any native browser implementation of Popover API?

**Comment by jgerigmeyer** [comment]
> Do you think it would be possible to, if `apply()` is called, override any native browser implementation of Popover API?

I'm not sure this would be feasible -- calling `apply()` directly should already attempt to override the native browser implementation, but I'm not sure the polyfill can also patch related browser bugs (like the `<form>` one you mention). @jamesnw What's your take here?

**Comment by jamesnw** [comment]
I agree, I'm not seeing a straightforward path to patch bugs in general, or this one in particular. I think the best case scenario would be patching Safari 17 behavior to get it to spec, instead of replacing Safari 17 behavior completely. However, I'm not sure we would want to expand the polyfill to cover patches like that.

**Comment by Techn1x** [comment]
Thanks for your thoughts about it both of you. I was hopeful for an easy solution but it's clear it's not that straightforward.

Not to worry - in the meantime I've come up with a workaround for Safari 17-18.2

Essentially it's: detect the safari version 17, detect if the button is in a form, and then if both of those are true apply a click handler to toggle the popover manually with javascript

I'll post it when I'm back from holiday in a few days, it might help some people

**Comment by Techn1x** [comment]
Here it is. Run this code on any buttons you have that have the `popovertarget` attribute. How you do that depends on the framework you use - eg modifiers in ember.js, hooks in liveview, etc

```ts
// If Safari >= 17 and < 18.2, if button is within form, open manually on click
const isWithinForm = Boolean('form' in buttonEl && buttonEl.form)
if (isWithinForm && isBetweenSafari17And182()) {
  buttonEl.addEventListener('click', () => {
    const popoverTargetId = buttonEl.getAttribute('popovertarget')
    if (popoverTargetId) document.getElementById(popoverTargetId)?.togglePopover()
  })
}
```

Here's the Safari >= 17 and < 18.2 detection code
```ts
import { isPolyfilled } from '@oddbird/popover-polyfill/fn'

function isBetweenSafari17And182() {
  const userAgent = navigator.userAgent
  const isSafari = /^((?!chrome|android).)*safari/i.test(userAgent)

  // if safari and not polyfilled (aka using native), must be after 17
  const isAtLeast17 = isSafari && !isPolyfilled()
  // a proxy for detecting v18.2 - Float16Array is a feature added in Safari 18.2
  const isBefore182 = isSafari && !window.Float16Array

  return isAtLeast17 && isBefore182
}
```
