### ISSUE TITLE
Clicking on slotted element closes the popover

### ISSUE THREAD

**Issue by Totati** [oddbird/popover-polyfill#214]
**Describe the bug**
Clicking on a slotted html element closes the popover.

**To Reproduce**

1. Go to [https://codepen.io/Totati/pen/abgOBPP](https://codepen.io/Totati/pen/abgOBPP)
2. Click on "Open popover" button.
3. Click on the red area. It's the slotted element.

Clicking in the green element does not closes the popover.

**Expected behavior**
This example works correctly in new browsers, the polyfill should handle this case as well :)

**Browsers tested on**
Chromium Version 101.0.4949.0 (Developer Build) (64-bit)

**Comment by jgerigmeyer** [comment]
Closed by #215

**Comment by Totati** [comment]
Could you publish a release to npm please?
