### ISSUE TITLE
[BUG] CSS is not published

### ISSUE THREAD

**Issue by felamaslen** [oddbird/popover-polyfill#219]
**Describe the bug**
CSS file is not present in `node_modules/@oddbird/popover-polyfill` upon running `npm install @oddbird/popover-polyfill`.

**To Reproduce**

1. Install the dependency: `npm install @oddbird/popover-polyfill`
2. Check `node_modules/@oddbird/popover-polyfill`

**Expected behavior**
A css file is present in this directory.

**Comment by jgerigmeyer** [comment]
This is intentional. Back in #137 we switched to automatically injecting the necessary CSS for the polyfill via JS: https://github.com/oddbird/popover-polyfill/blob/main/src/popover.ts#L57-L115
