### ISSUE TITLE
CJS support

### ISSUE THREAD

**Issue by myasonik** [oddbird/popover-polyfill#222]
**Is your feature request related to how popovers work in general?** No

**Is your feature request related to how this polyfill works? Please describe.**
My codebase only supports CJS packages while the polyfill is only bundled for ESM. 

**Describe the solution you'd like**
Include CJS support in the package.json. esbuild seems to support it out of the box. 

**Describe alternatives you've considered**
Not sure what other options there are.

**Comment by jgerigmeyer** [comment]
@myasonik Which entrypoint are you currently trying to `require` that's failing? Would #224 fix your use case?
