### ISSUE TITLE
Change of Attribute

### ISSUE THREAD

**Issue by richajak** [oddbird/popover-polyfill#33]
Should this library be updated to handle change of attribute from popup to popover ? I am testing it on my dev machine, should I just replace all occurence of 'popup' to 'popover' ? 

[https://developer.chrome.com/blog/pop-ups-theyre-making-a-resurgence/](url)

Thanks

**Comment by jgerigmeyer** [comment]
Renamed and published v0.0.3: https://www.npmjs.com/package/@oddbird/popover-polyfill
