### ISSUE TITLE
Update to 'popover'

### ISSUE THREAD

**Issue by una** [oddbird/popover-polyfill#35]
There was a [resolution](https://github.com/openui/open-ui/issues/627) in OpenUI to update this API to "popover" from "pop-up". The syntax has changed accordingly, and there is a [PR in](https://github.com/openui/open-ui/pull/629) to update the OpenUI site.

**Comment by jgerigmeyer** [comment]
Renamed and published v0.0.3: https://www.npmjs.com/package/@oddbird/popover-polyfill
