### ISSUE TITLE
Using popover inside shadowRoot

### ISSUE THREAD

**Issue by rinaok** [oddbird/popover-polyfill#44]
Hi!

We are trying to use popover polyfill within custom elements.

Since the popover attribute is inside the shadow root, it cannot be found.

This is a screenshot from `popover.js`, `doc.querySelectorAll('[popover="" i].\\:open, [popover=auto i].\\:open')`.

<img width="759" alt="Screenshot 2022-12-06 at 16 11 30" src="https://user-images.githubusercontent.com/10883919/205934607-7a8ebdf3-0ff3-40ec-8bca-45803e20bceb.png">

**Comment by yinonov** [comment]
Should this need a little JS boost? At least for the interim

**Comment by yinonov** [comment]
Would a PR be welcomed here?

**Comment by jgerigmeyer** [comment]
@yinonov Yes, a PR would be welcome!
